#!/usr/bin/env bash

mem="$(free | grep 'Mem')"

used="$(echo $mem | awk '{print $3}')"
total="$(echo $mem | awk '{print $2}')"

usedperc="$((${used} * 100 / ${total}))"

used=$(echo "scale=2; ${used} / 1000000" | bc)
total=$(echo "scale=2; ${total} / 1000000" | bc)

echo "RAM:     ${used}GB/${total}GB ($usedperc%)"